name: fasdf
description: asdf helper for symlinking versions defined in .tool-versions in your local project
version: 0.0.2
repository: https://github.com/exaby73/fasdf

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0

executables:
  fasdf:
